version: "3.8"

services:
    mainsailP0:
        image: ghcr.io/mainsail-crew/mainsail:latest
        ports:
            - "8080:8080"
        configs:
            - source: mainsailConfig0
              target: /usr/share/nginx/html/config.json
        deploy:
            replicas: 1

    mainsailP1:
        image: ghcr.io/mainsail-crew/mainsail:latest
        ports:
            - "8081:8080"
        configs:
            - source: mainsailConfig1
              target: /usr/share/nginx/html/config.json
        deploy:
            replicas: 1
            
    mainsailP2:
        image: ghcr.io/mainsail-crew/mainsail:latest
        ports:
            - "8082:8080"
        configs:
            - source: mainsailConfig2
              target: /usr/share/nginx/html/config.json
        deploy:
            replicas: 1

    # mainsailP3:
    #     image: ghcr.io/mainsail-crew/mainsail:latest
    #     ports:
    #         - "8083:8080"
    #     configs:
    #         - source: mainsailConfig3
    #           target: /usr/share/nginx/html/config.json
    #     deploy:
    #         replicas: 1
    #         
    # mainsailP4:
    #     image: ghcr.io/mainsail-crew/mainsail:latest
    #     ports:
    #         - "8084:8080"
    #     configs:
    #         - source: mainsailConfig4
    #           target: /usr/share/nginx/html/config.json
    #     deploy:
    #         replicas: 1
configs:
    mainsailConfig0:
        file: ./mainSailConfigs/config0.json
    mainsailConfig1:
        file: ./mainSailConfigs/config1.json
    mainsailConfig2:
        file: ./mainSailConfigs/config2.json
    mainsailConfig3:
        file: ./mainSailConfigs/config3.json
    mainsailConfig4:
        file: ./mainSailConfigs/config4.json
